version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
    image: frontend_production
    container_name: frontend_production
    volumes:
      - "./frontend:/frontend"
      - build-cache:/frontend/build
  backend:
    build:
      context: ./backend
    image: backend_production
    container_name: backend_production
    ports:
      - "8088:8088"
    volumes:
      - ./backend:/backend
      - build-cache:/frontend/build
    depends_on:
      - frontend
    command: /bin/sh -c "lyrian_web"

volumes:
  build-cache:
