version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      target: "dev-stage"
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/lyrian_web"
      - modules-cache:/lyrian_web/node_modules
    command: /bin/sh -c "yarn start"
  backend:
    build:
      context: ./backend
      target: "dev-stage"
    ports:
      - "8088:8088"
    volumes:
      - ./backend:/lyrian_web
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/lyrian_web/target
    command: /bin/sh -c "cargo watch -x run"

volumes:
  modules-cache:
  cargo-cache:
  target-cache:
